const BOARD_START = [
  [
    { type: "Rok", id: "r_b_0", isWhite: false },
    // { type: "Knight", id: "kt_b_0", isWhite: false },
    // { type: "Bishop", id: "b_b_0", isWhite: false },
    null,
    null,
    null,
    // { type: "Queen", id: "q_b_0", isWhite: false },
    { type: "King", id: "kg_b_0", isWhite: false },
    // { type: "Bishop", id: "b_b_0", isWhite: false },
    // { type: "Knight", id: "kt_b_1", isWhite: false },
    null,
    null,
    { type: "Rok", id: "r_b_1", isWhite: false },
  ],
  [
    { type: "Pawn", id: "p_b_0", isWhite: false },
    { type: "Pawn", id: "p_b_1", isWhite: false },
    { type: "Pawn", id: "p_b_2", isWhite: false },
    { type: "Pawn", id: "p_b_3", isWhite: false },
    { type: "Pawn", id: "p_b_4", isWhite: false },
    { type: "Pawn", id: "p_b_5", isWhite: false },
    { type: "Pawn", id: "p_b_6", isWhite: false },
    { type: "Pawn", id: "p_b_7", isWhite: false },
  ],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [
    { type: "Pawn", id: "p_w_0", isWhite: true },
    { type: "Pawn", id: "p_w_1", isWhite: true },
    { type: "Pawn", id: "p_w_2", isWhite: true },
    { type: "Pawn", id: "p_w_3", isWhite: true },
    { type: "Pawn", id: "p_w_4", isWhite: true },
    { type: "Pawn", id: "p_w_5", isWhite: true },
    { type: "Pawn", id: "p_w_6", isWhite: true },
    { type: "Pawn", id: "p_w_7", isWhite: true },
  ],
  [
    { type: "Rok", id: "r_w_0", isWhite: true },
    // { type: "Knight", id: "kt_w_0", isWhite: true },
    // { type: "Bishop", id: "b_w_0", isWhite: true },
    null,
    null,
    { type: "King", id: "kg_w_0", isWhite: true },
    // { type: "Queen", id: "q_w_0", isWhite: true },
    // { type: "Bishop", id: "b_w_1", isWhite: true },
    // { type: "Knight", id: "kt_w_1", isWhite: true },
    null,
    null,
    null,

    { type: "Rok", id: "r_w_1", isWhite: true },
  ],
];

export { BOARD_START };
