const BOARD_START = [
  [
    null,
    { type: "King", id: "k0", isWhite: true },
    { type: "Rok", id: "r0", isWhite: true },
    { type: "Knight", id: "kg0", isWhite: true },
    null,
    null,
    { type: "Knight", id: "kg2", isWhite: true },
    ,
    null,
  ],
  [
    { type: "Pawn", id: "p0", isWhite: true },
    { type: "Pawn", id: "p1", isWhite: true },
    { type: "Pawn", id: "p2", isWhite: true },
    { type: "Pawn", id: "p3", isWhite: true },
    { type: "Pawn", id: "p4", isWhite: true },
    { type: "Pawn", id: "p5", isWhite: true },
    { type: "Pawn", id: "p6", isWhite: true },
    { type: "Pawn", id: "p7", isWhite: true },
  ],
  [
    null,
    { type: "Pawn", id: "p0", isWhite: false },
    null,
    null,
    null,
    null,
    { type: "King", id: "k0", isWhite: false },
    null,
  ],
  [null, null, null, null, null, null, null, null],
  [
    null,
    null,
    null,
    { type: "Knight", id: "kg0", isWhite: true },
    null,
    null,
    { type: "Rok", id: "r0", isWhite: true },
    null,
  ],
  [
    null,
    { type: "Pawn", id: "p3", isWhite: false },
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  [
    { type: "Pawn", id: "p0", isWhite: false },
    { type: "Rok", id: "r0", isWhite: true },
    null,
    { type: "Pawn", id: "p3", isWhite: false },
    { type: "Pawn", id: "p4", isWhite: false },
    { type: "Pawn", id: "p5", isWhite: false },
    { type: "Pawn", id: "p6", isWhite: false },
    { type: "Pawn", id: "p7", isWhite: false },
  ],
  [
    null,
    { type: "Knight", id: "kg2", isWhite: false },
    null,
    null,
    { type: "Rok", id: "r0", isWhite: true },
    ,
    null,
    { type: "Knight", id: "kg2", isWhite: false },
    ,
    null,
  ],
];

export { BOARD_START };
